<a href="https://colab.research.google.com/github/Adassa86/Hackathon2/blob/main/Copie_de_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files 
import io
uploaded= files.upload()

Saving classeur11.xlsx to classeur11 (4).xlsx

In [ ]:
df= pd.read_excel(io.BytesIO(uploaded['classeur11.xlsx']))

In [ ]:
df

      col1                                  col2   col3
0      NaN                                   NaN    NaN
1      96%                  Black Panther (2018)  525.0
2      94%              Avengers: Endgame (2019)  547.0
3      97%  Mission: Impossible - Fallout (2018)  437.0
4      97%             Mad Max: Fury Road (2015)  434.0
..     ...                                   ...    ...
96     96%                      Apollo 13 (1995)   93.0
97     93%                  The Lion King (1994)  130.0
98     88%                   Annihilation (2018)  324.0
99     96%            Catch Me If You Can (2002)  203.0
100    97%        Who Framed Roger Rabbit (1988)   66.0

[101 rows x 3 columns]

In [ ]:
df.sort_values(by=['col1'])

      col1                                         col2   col3
11    100%  Seven Samurai (Shichinin no Samurai) (1956)   87.0
58    100%    The Taking of Pelham One Two Three (1974)   43.0
27    100%      The Treasure of the Sierra Madre (1948)   52.0
49    100%                            Stagecoach (1939)   45.0
15    100%          The Adventures of Robin Hood (1938)   48.0
..     ...                                          ...    ...
37     98%                        Apocalypse Now (1979)   96.0
24     98%                                    Up (2009)  298.0
17     98%                             King Kong (1933)   66.0
48     99%                            Goldfinger (1964)   69.0
0      NaN                                          NaN    NaN

[101 rows x 3 columns]

In [ ]:
df.sort_values(by=['col1']).head(25)

      col1                                         col2   col3
11    100%  Seven Samurai (Shichinin no Samurai) (1956)   87.0
58    100%    The Taking of Pelham One Two Three (1974)   43.0
27    100%      The Treasure of the Sierra Madre (1948)   52.0
49    100%                            Stagecoach (1939)   45.0
15    100%          The Adventures of Robin Hood (1938)   48.0
74    100%                               Stalker (1979)   41.0
53    100%                        The Terminator (1984)   65.0
82    100%                               Henry V (1989)   40.0
77     79%                        Captain Marvel (2019)  543.0
89     84%                            Deadpool 2 (2018)  420.0
38     85%                Avengers: Infinity War (2018)  485.0
73     85%        Guardians of the Galaxy Vol. 2 (2017)  422.0
42     87%                  Ant-Man and the Wasp (2018)  438.0
29     88%                     Blade Runner 2049 (2017)  442.0
98     88%                          Annihilation (2018)  324.0
80     88%                                Onward (2020)  337.0
59     89%     John Wick: Chapter 3 - Parabellum (2019)  353.0
56     89%                        Doctor Strange (2016)  385.0
25     90%                               Shazam! (2019)  413.0
76     90%        Dawn Of The Planet Of The Apes (2014)  315.0
28     90%            Captain America: Civil War (2016)  426.0
44     90%                          Isle of Dogs (2018)  367.0
88     90%   Captain America: The Winter Soldier (2014)  306.0
19     90%             Spider-Man: Far From Home (2019)  451.0
70     90%                 The Lego Batman Movie (2017)  313.0